### ISSUE TITLE
32 bit Wiegand support

### ISSUE THREAD

**Issue by vrelk** [cyrusbuilt/HidProxWeigand#7]
**This has been turned into a pull request, but I will leave this here anyway.**

Add the following after line 19 in HidProxWeigand.h
`#define CARD_FORMAT_WEIGAND_32    32  // Standard 32bit Weigand format.`

Add the following after line 113 in HidProxWeigand.cpp
```
else if (this->_currentReader->bitCount == CARD_FORMAT_WEIGAND_32) {
                // Standard 32bit weigand format.
                // Facility code is bits 5 to 16.
                facStartBit = 4;
                facStopBit = 16;

                // Card code is bits 17 to 32;
                cardStartBit = 16;
                cardStopBit = 32;
            }
```

[Here is an awesome site for creating custom formats](http://cardinfo.barkweb.com.au/)
```

**Comment by cyrusbuilt** [comment]
Merged PR #8
